data:extend{
    {
        type = "fluid",
        name = "molten-iron",
        default_temperature = 2000,
        max_temperature = 2000,
        heat_capacity = "1KJ",
        base_color = {r=1, g=0.47, b=0.01},
        flow_color = {r=0.7, g=0.7, b=0.7},
        icon = "__environtorio__/graphics/icons/molten-iron.png",
        icon_size = 64, icon_mipmaps = 4,
        order = "a[fluid]-a[molten-iron]"
    },
    {
        type = "fluid",
        name = "molten-copper",
        default_temperature = 2000,
        max_temperature = 2000,
        heat_capacity = "1KJ",
        base_color = {r=1, g=0.47, b=0.01},
        flow_color = {r=0.7, g=0.7, b=0.7},
        icon = "__environtorio__/graphics/icons/molten-copper.png",
        icon_size = 64, icon_mipmaps = 4,
        order = "a[fluid]-a[molten-copper]"
    },
    {
        type = "fluid",
        name = "molten-steel",
        default_temperature = 2000,
        max_temperature = 2000,
        heat_capacity = "1KJ",
        base_color = {r=1, g=0.47, b=0.01},
        flow_color = {r=0.7, g=0.7, b=0.7},
        icon = "__environtorio__/graphics/icons/molten-steel.png",
        icon_size = 64, icon_mipmaps = 4,
        order = "a[fluid]-a[molten-steel]"
    },
    {
        type = "fluid",
        name = "liquid-plastic",
        default_temperature = 300,
        max_temperature = 300,
        heat_capacity = "1KJ",
        base_color = {r=1, g=0.47, b=0.01},
        flow_color = {r=0.7, g=0.7, b=0.7},
        icon = "__environtorio__/graphics/icons/molten-glass.png",
        icon_size = 64, icon_mipmaps = 4,
        order = "a[fluid]-a[liquid-plastic]"
    },
    {
        type = "fluid",
        name = "molten-glass",
        default_temperature = 2000,
        max_temperature = 2000,
        heat_capacity = "1KJ",
        base_color = {r=1, g=0.47, b=0.01},
        flow_color = {r=0.7, g=0.7, b=0.7},
        icon = "__environtorio__/graphics/icons/molten-glass.png",
        icon_size = 64, icon_mipmaps = 4,
        order = "a[fluid]-a[molten-glass]"
    },
    {
        type = "fluid",
        name = "molten-silicon",
        default_temperature = 2000,
        max_temperature = 2000,
        heat_capacity = "1KJ",
        base_color = {r=1, g=0.47, b=0.01},
        flow_color = {r=0.7, g=0.7, b=0.7},
        icon = "__environtorio__/graphics/icons/molten-silicon.png",
        icon_size = 64, icon_mipmaps = 4,
        order = "a[fluid]-a[molten-silicon]"
    },
    {
        type = "fluid",
        name = "molten-rare-metals",
        default_temperature = 2000,
        max_temperature = 2000,
        heat_capacity = "1KJ",
        base_color = {r=1, g=0.47, b=0.01},
        flow_color = {r=0.7, g=0.7, b=0.7},
        icon = "__environtorio__/graphics/icons/molten-raremetals.png",
        icon_size = 64, icon_mipmaps = 4,
        order = "a[fluid]-a[molten-rare-metals]"
    },
    {
        type = "fluid",
        name = "molten-imersium",
        default_temperature = 2000,
        max_temperature = 2000,
        heat_capacity = "1KJ",
        base_color = {r=1, g=0.47, b=0.01},
        flow_color = {r=0.7, g=0.7, b=0.7},
        icon = "__environtorio__/graphics/icons/molten-imersite.png",
        icon_size = 64, icon_mipmaps = 4,
        order = "a[fluid]-a[molten-imersium]"
    },
}