data:extend{
    {
        type = "recipe",
        name = "basic-iron-melting",
        energy_required = 24,
        enabled = false,
        category = "metallurgy",
        always_show_made_in = true,
        ingredients = {
            {type="item", name = "iron-ore", amount = 40},
            {type="fluid", name = "oxygen", amount = 300}
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "smelting",
        order = "ma[basic-iron-melting]",
        results = {
            {type="fluid", name = "molten-iron", amount = 750 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-copper-melting",
        energy_required = 24,
        enabled = false,
        category = "metallurgy",
        always_show_made_in = true,
        ingredients = {
            {type="item", name = "copper-ore", amount = 40},
            {type="fluid", name = "oxygen", amount = 300}
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "smelting",
        order = "ma[basic-copper-melting]",
        results = {
            {type="fluid", name = "molten-copper", amount = 750 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-rare-metals-melting",
        energy_required = 24,
        enabled = false,
        category = "metallurgy",
        always_show_made_in = true,
        ingredients = {
            {type="item", name = "raw-rare-metals", amount = 40},
            {type="fluid", name = "oxygen", amount = 300}
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "smelting",
        order = "ma[basic-rare-metals-melting]",
        results = {
            {type="fluid", name = "molten-rare-metals", amount = 750 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "advanced-iron-melting",
        energy_required = 24,
        enabled = false,
        category = "metallurgy",
        always_show_made_in = true,
        ingredients = {
            {type="item", name = "iron-ore", amount = 40},
            {type="fluid", name = "oxygen", amount = 300},
            {type="fluid", name = "magmacyte", amount = 40},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "smelting",
        order = "ma[advanced-iron-melting]",
        results = {
            {type="fluid", name = "molten-iron", amount = 1000 },
        },
        main_product = ""
    },
    {
        type = "recipe",
        name = "advanced-copper-melting",
        energy_required = 24,
        enabled = false,
        category = "metallurgy",
        always_show_made_in = true,
        ingredients = {
            {type="item", name = "copper-ore", amount = 40},
            {type="fluid", name = "oxygen", amount = 300},
            {type="fluid", name = "magmacyte", amount = 40},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "smelting",
        order = "ma[advanced-copper-melting]",
        results = {
            {type="fluid", name = "molten-copper", amount = 1000 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "advanced-rare-metals-melting",
        energy_required = 24,
        enabled = false,
        category = "metallurgy",
        always_show_made_in = true,
        ingredients = {
            {type="item", name = "raw-rare-metals", amount = 40},
            {type="fluid", name = "oxygen", amount = 300},
            {type="fluid", name = "magmacyte", amount = 40},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "smelting",
        order = "ma[advanced-rare-metals-melting]",
        results = {
            {type="fluid", name = "molten-rare-metals", amount = 1000 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-steel-infusing",
        energy_required = 12,
        enabled = true,
        category = "metallurgic-infusing",
        always_show_made_in = true,
        ingredients = {
            {type="item", name = "coke", amount = 4},
            {type="fluid", name = "molten-iron", amount = 250}
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "infusing",
        order = "na[basic-steel-infusing]",
        results = {
            {type="fluid", name = "molten-steel", amount = 125 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-imersium-infusing",
        energy_required = 12,
        enabled = true,
        category = "metallurgic-infusing",
        always_show_made_in = true,
        ingredients = {
            {type="item", name = "imersite-powder", amount = 10},
            {type="fluid", name = "molten-rare-metals", amount = 250}
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "infusing",
        order = "na[basic-imersium-infusing]",
        results = {
            {type="fluid", name = "molten-imersium", amount = 250 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "advanced-silicon-purification",
        energy_required = 12,
        enabled = true,
        category = "fluid-filtration",
        always_show_made_in = true,
        ingredients = {
            {type="item", name = "imersite-powder", amount = 10},
            {type="fluid", name = "molten-rare-metals", amount = 250}
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "infusing",
        order = "na[basic-imersium-infusing]",
        results = {
            {type="fluid", name = "molten-imersium", amount = 250 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "advanced-glass-melting",
        energy_required = 10,
        enabled = true,
        category = "metallurgy",
        always_show_made_in = true,
        ingredients = {
            {type="item", name = "sand", amount = 20},
            {type="fluid", name = "oxygen", amount = 125}
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "smelting",
        order = "mb[basic-copper-melting]",
        results = {
            {type="fluid", name = "molten-glass", amount = 200 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-iron-plate-casting",
        energy_required = 16,
        enabled = false,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-iron", amount = 250},
            {type="fluid", name = "water", amount = 1000},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "iron-casting",
        order = "oa[basic-iron-plate-casting]",
        results = {
            {type="item", name = "iron-plate", amount = 10 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-iron-stick-casting",
        energy_required = 10,
        enabled = false,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-iron", amount = 375},
            {type="fluid", name = "water", amount = 1500},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "iron-casting",
        order = "oa[basic-iron-stick-casting]",
        results = {
            {type="item", name = "iron-stick", amount = 30 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-iron-gear-casting",
        energy_required = 10,
        enabled = false,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-iron", amount = 375},
            {type="fluid", name = "water", amount = 1500},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "iron-casting",
        order = "oa[basic-iron-gear-casting]",
        results = {
            {type="item", name = "iron-gear-wheel", amount = 15 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-iron-beam-casting",
        energy_required = 20,
        enabled = false,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-iron", amount = 750},
            {type="fluid", name = "water", amount = 3000},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "iron-casting",
        order = "oa[basic-iron-plate-casting]",
        results = {
            {type="item", name = "iron-beam", amount = 15 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-copper-plate-casting",
        energy_required = 16,
        enabled = false,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-copper", amount = 250},
            {type="fluid", name = "water", amount = 1000},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "copper-casting",
        order = "ob[basic-copper-plate-casting]",
        results = {
            {type="item", name = "copper-plate", amount = 10 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-copper-cable-casting",
        energy_required = 10,
        enabled = false,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-copper", amount = 375},
            {type="fluid", name = "water", amount = 1500},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "copper-casting",
        order = "ob[basic-copper-cable-casting]",
        results = {
            {type="item", name = "copper-cable", amount = 30 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "advanced-glass-casting",
        energy_required = 10,
        enabled = true,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-glass", amount = 100},
            {type="fluid", name = "water", amount = 1000},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "casting",
        order = "od[basic-glass-casting]",
        results = {
            {type="item", name = "glass", amount = 10 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-steel-plate-casting",
        energy_required = 16,
        enabled = false,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-steel", amount = 250},
            {type="fluid", name = "water", amount = 1000},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "steel-casting",
        order = "oc[basic-steel-plate-casting]",
        results = {
            {type="item", name = "steel-plate", amount = 10 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-steel-gear-casting",
        energy_required = 10,
        enabled = true,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-steel", amount = 375},
            {type="fluid", name = "water", amount = 1500},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "steel-casting",
        order = "oc[basic-steel-gear-casting]",
        results = {
            {type="item", name = "steel-gear-wheel", amount = 15 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-steel-beam-casting",
        energy_required = 20,
        enabled = true,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-steel", amount = 750},
            {type="fluid", name = "water", amount = 3000},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "steel-casting",
        order = "oc[basic-steel-beam-casting]",
        results = {
            {type="item", name = "steel-beam", amount = 15 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-rare-metals-casting",
        energy_required = 16,
        enabled = false,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-rare-metals", amount = 250},
            {type="fluid", name = "water", amount = 1000},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "casting",
        order = "oc[basic-rare-metals-casting]",
        results = {
            {type="item", name = "rare-metals", amount = 10 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-imersium-plate-casting",
        energy_required = 16,
        enabled = true,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-imersium", amount = 250},
            {type="fluid", name = "water", amount = 1000},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "imersium-casting",
        order = "og[basic-imersium-plate-casting]",
        results = {
            {type="item", name = "imersium-plate", amount = 10 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-imersium-gear-casting",
        energy_required = 10,
        enabled = true,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-imersium", amount = 375},
            {type="fluid", name = "water", amount = 1500},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "imersium-casting",
        order = "og[basic-imersium-gear-casting]",
        results = {
            {type="item", name = "imersium-gear-wheel", amount = 15 },
        },
        main_product = "",
    },
    {
        type = "recipe",
        name = "basic-imersium-beam-casting",
        energy_required = 20,
        enabled = true,
        category = "casting",
        always_show_made_in = true,
        ingredients = {
            {type="fluid", name = "molten-imersium", amount = 750},
            {type="fluid", name = "water", amount = 3000},
        },
        icon = "__environtorio__/graphics/icons/molten-metal.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "imersium-casting",
        order = "og[basic-imersium-beam-casting]",
        results = {
            {type="item", name = "imersium-beam", amount = 15 },
        },
        main_product = "",
    },
    -- barrels
    -- pipe
    -- steel pipe
    -- underground pipe
    -- steel underground pipe
    
    -- inserter parts 2 iron
    -- automation cores 2 copper 1 iron
    -- electronic components 2 glass 2 silicon 2 plastic
    -- lds 2 steel 10 copper 5 plastic
    -- engine unit 3 iron
    
}
